export const ROOT = '/'
export const CHARACTER = '/Character'
export const SKILLS ='/skills'
export const USERS ='/users'
export const LOGIN = '/login'
export const ITEM = '/item'
export const SEARCH = '/SEARCH'
export const REGISTER = '/REGISTER'
